config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks

  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    p params
    @task = Task.new(task_params)
    p @task
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
  @task.update(task_params)
  redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

 <%= f.label :completed %>
 <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>To-Do</h1>
<ul>
  <% @tasks.each do |task| %>
  <li> <%= link_to "#{task.name} Completed: #{task.completed}", task_path(task) %>
    <ul>
      <li><%= link_to "delete", task_path(task), method: :delete %> <%= link_to "edit", edit_task_path(task) %> </li>
    </ul>
  </li>

  <% end %>
</ul>

<p> <%= link_to "Add new", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>Create a task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p><%= "Completed: #{@task.completed} "%></p>

<p><%=link_to "home", tasks_path %></p>